"""Add allow_registrations to Shop

Revision ID: 3babf65e75c1
Revises: 52b96468a5aa
Create Date: 2025-07-24 01:39:28.260459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3babf65e75c1'
down_revision = '52b96468a5aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('allow_registrations', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'allow_registrations')
    # ### end Alembic commands ###
