"""empty message

Revision ID: 52b96468a5aa
Revises: 29dd512f936e
Create Date: 2025-07-23 22:56:47.783323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52b96468a5aa'
down_revision = '29dd512f936e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('slug', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_shops_slug'), 'shops', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shops_slug'), table_name='shops')
    op.drop_column('shops', 'slug')
    # ### end Alembic commands ###
