"""empty message

Revision ID: 1ec27b47e821
Revises: a20414556111
Create Date: 2025-08-01 09:26:22.057092

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ec27b47e821'
down_revision = 'a20414556111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'businesses', 'users', ['approved_by_id'], ['id'])
    op.add_column('cart_items', sa.Column('discount', sa.Numeric(precision=5, scale=2), nullable=True))
    op.alter_column('cart_items', 'quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=12, scale=3),
               existing_nullable=False)
    op.alter_column('cart_items', 'unit_price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
    op.alter_column('cart_items', 'total_price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart_items', 'total_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cart_items', 'unit_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cart_items', 'quantity',
               existing_type=sa.Numeric(precision=12, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('cart_items', 'discount')
    op.drop_constraint(None, 'businesses', type_='foreignkey')
    # ### end Alembic commands ###
