"""empty message

Revision ID: 516fe9f14457
Revises: 97b48d5e8c3d
Create Date: 2025-07-19 10:53:19.285157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516fe9f14457'
down_revision = '97b48d5e8c3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'businesses', 'users', ['approved_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'businesses', type_='foreignkey')
    # ### end Alembic commands ###
