"""empty message

Revision ID: 78ff0727ed1b
Revises: 516fe9f14457
Create Date: 2025-07-19 13:32:06.268431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ff0727ed1b'
down_revision = '516fe9f14457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('minimum_quantity', sa.Numeric(precision=4, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'minimum_quantity')
    # ### end Alembic commands ###
