"""empty message

Revision ID: b981d4efec6e
Revises: 
Create Date: 2025-07-26 13:12:49.537279

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'b981d4efec6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('secondary_phone', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.Column('tax_identification', sa.String(length=50), nullable=True),
    sa.Column('business_type', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('fiscal_year_start', sa.Date(), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'CLOSED', 'PENDING', name='businessstatus'), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('banner_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('registration_number'),
    sa.UniqueConstraint('tax_identification')
    )
    op.create_index('ix_business_approved', 'businesses', ['is_approved'], unique=False)
    op.create_index('ix_business_status', 'businesses', ['status'], unique=False)
    op.create_index(op.f('ix_businesses_is_approved'), 'businesses', ['is_approved'], unique=False)
    op.create_index(op.f('ix_businesses_is_deleted'), 'businesses', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_businesses_name'), 'businesses', ['name'], unique=True)
    op.create_index(op.f('ix_businesses_status'), 'businesses', ['status'], unique=False)
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('allow_registrations', sa.Boolean(), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('type', sa.Enum('pos', 'pop', name='shoptype'), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index('ix_shops_business_id', 'shops', ['business_id'], unique=False)
    op.create_index('ix_shops_is_active', 'shops', ['is_active'], unique=False)
    op.create_index(op.f('ix_shops_is_deleted'), 'shops', ['is_deleted'], unique=False)
    op.create_index('ix_shops_name', 'shops', ['name'], unique=False)
    op.create_index('ix_shops_phone', 'shops', ['phone'], unique=False)
    op.create_index(op.f('ix_shops_slug'), 'shops', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_password_change', sa.DateTime(), nullable=True),
    sa.Column('login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('reset_token', sa.String(length=100), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.Column('email_verification_token', sa.String(length=100), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('SUPERADMIN', 'TENANT', 'ADMIN', 'CASHIER', name='role'), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_business', 'users', ['business_id'], unique=False)
    op.create_index('ix_user_role', 'users', ['role'], unique=False)
    op.create_index('ix_user_shop', 'users', ['shop_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'name', name='uq_category_shop_name')
    )
    op.create_index(op.f('ix_categories_is_deleted'), 'categories', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_table('register_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('opening_cash', sa.Float(), nullable=False),
    sa.Column('closing_cash', sa.Float(), nullable=True),
    sa.Column('expected_cash', sa.Float(), nullable=True),
    sa.Column('discrepancy', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('opened_by_id', sa.Integer(), nullable=False),
    sa.Column('closed_by_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opened_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_register_closed_at', 'register_sessions', ['closed_at'], unique=False)
    op.create_index('ix_register_closed_by', 'register_sessions', ['closed_by_id'], unique=False)
    op.create_index('ix_register_opened_at', 'register_sessions', ['opened_at'], unique=False)
    op.create_index('ix_register_opened_by', 'register_sessions', ['opened_by_id'], unique=False)
    op.create_index(op.f('ix_register_sessions_is_deleted'), 'register_sessions', ['is_deleted'], unique=False)
    op.create_index('ix_register_shop_closed', 'register_sessions', ['shop_id', 'closed_at'], unique=False)
    op.create_index('ix_register_shop_date', 'register_sessions', ['shop_id', 'opened_at'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_is_deleted'), 'suppliers', ['is_deleted'], unique=False)
    op.create_table('taxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('kra_code', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'name', name='uq_tax_name_per_shop')
    )
    op.create_index(op.f('ix_taxes_is_deleted'), 'taxes', ['is_deleted'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('stock', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), server_default=sa.text('10'), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('secondary_images', sqlalchemy_utils.types.scalar_list.ScalarListType(), nullable=True),
    sa.Column('unit', sa.Enum('PIECE', 'KILOGRAM', 'GRAM', 'LITER', 'MILLILITER', 'PACKET', 'BOTTLE', 'BOX', 'METER', 'CENTIMETER', name='unittype'), nullable=True),
    sa.Column('minimum_unit', sa.Numeric(precision=3, scale=2), server_default=sa.text('1.0'), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('combination_size', sa.Integer(), nullable=True),
    sa.Column('combination_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('combination_unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('is_featured', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('is_discountable', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_barcode_shop', 'products', ['barcode', 'shop_id'], unique=False)
    op.create_index('ix_product_name_shop', 'products', ['name', 'shop_id'], unique=False)
    op.create_index('ix_product_search', 'products', ['shop_id', 'name', 'barcode', 'sku'], unique=False)
    op.create_index('ix_product_shop_active', 'products', ['shop_id', 'is_active'], unique=False)
    op.create_index('ix_product_shop_category', 'products', ['shop_id', 'category_id'], unique=False)
    op.create_index('ix_product_shop_combo', 'products', ['shop_id', 'combination_size'], unique=False)
    op.create_index('ix_product_shop_stock', 'products', ['shop_id', 'stock'], unique=False)
    op.create_index('ix_product_shop_supplier', 'products', ['shop_id', 'supplier_id'], unique=False)
    op.create_index('ix_product_sku_shop', 'products', ['sku', 'shop_id'], unique=False)
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_is_deleted'), 'products', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_index(op.f('ix_products_supplier_id'), 'products', ['supplier_id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('register_session_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['register_session_id'], ['register_sessions.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sale_date', 'sales', ['date'], unique=False)
    op.create_index('ix_sale_payment', 'sales', ['payment_method'], unique=False)
    op.create_index('ix_sale_session', 'sales', ['register_session_id'], unique=False)
    op.create_index('ix_sale_shop_date', 'sales', ['shop_id', 'date'], unique=False)
    op.create_index('ix_sale_shop_pay_date', 'sales', ['shop_id', 'payment_method', 'date'], unique=False)
    op.create_index('ix_sale_total', 'sales', ['total'], unique=False)
    op.create_index('ix_sale_user', 'sales', ['user_id'], unique=False)
    op.create_index(op.f('ix_sales_date'), 'sales', ['date'], unique=False)
    op.create_index(op.f('ix_sales_is_deleted'), 'sales', ['is_deleted'], unique=False)
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_items_is_deleted'), 'cart_items', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_cart_items_product_id'), 'cart_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_cart_items_sale_id'), 'cart_items', ['sale_id'], unique=False)
    op.create_index('ix_cartitem_product_sale', 'cart_items', ['product_id', 'sale_id'], unique=False)
    op.create_index('ix_cartitem_sale_product', 'cart_items', ['sale_id', 'product_id'], unique=False)
    op.create_index('ix_cartitem_shop_product', 'cart_items', ['shop_id', 'product_id'], unique=False)
    op.create_index('ix_cartitem_shop_sale', 'cart_items', ['shop_id', 'sale_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_expense_date_category', 'expenses', ['date', 'category'], unique=False)
    op.create_index(op.f('ix_expenses_date'), 'expenses', ['date'], unique=False)
    op.create_index(op.f('ix_expenses_is_deleted'), 'expenses', ['is_deleted'], unique=False)
    op.create_table('price_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('old_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('new_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('old_combo_size', sa.Integer(), nullable=True),
    sa.Column('old_combo_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('new_combo_size', sa.Integer(), nullable=True),
    sa.Column('new_combo_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_changes_is_deleted'), 'price_changes', ['is_deleted'], unique=False)
    op.create_table('stock_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('previous_stock', sa.Integer(), nullable=False),
    sa.Column('new_stock', sa.Integer(), nullable=False),
    sa.Column('adjustment_type', sa.Enum('addition', 'reduction', 'returned', 'inventory_adjustment', 'damage', name='adjustmenttype'), nullable=False),
    sa.Column('change_reason', sa.String(length=200), nullable=True),
    sa.Column('log_metadata', sa.JSON(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_logs_is_deleted'), 'stock_logs', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_logs_is_deleted'), table_name='stock_logs')
    op.drop_table('stock_logs')
    op.drop_index(op.f('ix_price_changes_is_deleted'), table_name='price_changes')
    op.drop_table('price_changes')
    op.drop_index(op.f('ix_expenses_is_deleted'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_date'), table_name='expenses')
    op.drop_index('ix_expense_date_category', table_name='expenses')
    op.drop_table('expenses')
    op.drop_index('ix_cartitem_shop_sale', table_name='cart_items')
    op.drop_index('ix_cartitem_shop_product', table_name='cart_items')
    op.drop_index('ix_cartitem_sale_product', table_name='cart_items')
    op.drop_index('ix_cartitem_product_sale', table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_sale_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_product_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_is_deleted'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_sales_is_deleted'), table_name='sales')
    op.drop_index(op.f('ix_sales_date'), table_name='sales')
    op.drop_index('ix_sale_user', table_name='sales')
    op.drop_index('ix_sale_total', table_name='sales')
    op.drop_index('ix_sale_shop_pay_date', table_name='sales')
    op.drop_index('ix_sale_shop_date', table_name='sales')
    op.drop_index('ix_sale_session', table_name='sales')
    op.drop_index('ix_sale_payment', table_name='sales')
    op.drop_index('ix_sale_date', table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_products_supplier_id'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_is_deleted'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_index('ix_product_sku_shop', table_name='products')
    op.drop_index('ix_product_shop_supplier', table_name='products')
    op.drop_index('ix_product_shop_stock', table_name='products')
    op.drop_index('ix_product_shop_combo', table_name='products')
    op.drop_index('ix_product_shop_category', table_name='products')
    op.drop_index('ix_product_shop_active', table_name='products')
    op.drop_index('ix_product_search', table_name='products')
    op.drop_index('ix_product_name_shop', table_name='products')
    op.drop_index('ix_product_barcode_shop', table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_taxes_is_deleted'), table_name='taxes')
    op.drop_table('taxes')
    op.drop_index(op.f('ix_suppliers_is_deleted'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index('ix_register_shop_date', table_name='register_sessions')
    op.drop_index('ix_register_shop_closed', table_name='register_sessions')
    op.drop_index(op.f('ix_register_sessions_is_deleted'), table_name='register_sessions')
    op.drop_index('ix_register_opened_by', table_name='register_sessions')
    op.drop_index('ix_register_opened_at', table_name='register_sessions')
    op.drop_index('ix_register_closed_by', table_name='register_sessions')
    op.drop_index('ix_register_closed_at', table_name='register_sessions')
    op.drop_table('register_sessions')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_is_deleted'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_user_shop', table_name='users')
    op.drop_index('ix_user_role', table_name='users')
    op.drop_index('ix_user_business', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_shops_slug'), table_name='shops')
    op.drop_index('ix_shops_phone', table_name='shops')
    op.drop_index('ix_shops_name', table_name='shops')
    op.drop_index(op.f('ix_shops_is_deleted'), table_name='shops')
    op.drop_index('ix_shops_is_active', table_name='shops')
    op.drop_index('ix_shops_business_id', table_name='shops')
    op.drop_table('shops')
    op.drop_index(op.f('ix_businesses_status'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_name'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_is_deleted'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_is_approved'), table_name='businesses')
    op.drop_index('ix_business_status', table_name='businesses')
    op.drop_index('ix_business_approved', table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
